### ISSUE TITLE
Integrity constraint violation, duplicate entry

### ISSUE THREAD

**Issue by chrisonderwater** [ICEPAY/Magento#1]
On a website that I am currently working on sometimes, in about 1 in 200 orders, an error is shown to the user after checking out. The payment seems to process normally and the order is placed in the backend. 

The exception:

```
a:5:{i:0;s:164:"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '50800-50759-16225848' for key 'UNQ_OZSS_SALES_PAYMENT_TRANSACTION_ORDER_ID_PAYMENT_ID_TXN_ID'";i:1;s:3280:"#0 /var/www/vhosts/example.nl/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/vhosts/example.nl/httpdocs/app/code/core/Zend/Db/Statement.php(311): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/vhosts/example.nl/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/vhosts/example.nl/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ma...', Array)
#4 /var/www/vhosts/example.nl/httpdocs/.modman/Ho_Patches/app/code/community/Varien/Db/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ma...', Array)
#5 /var/www/vhosts/example.nl/httpdocs/lib/Zend/Db/Adapter/Abstract.php(576): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ma...', Array)
#6 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(453): Zend_Db_Adapter_Abstract->insert('mage_sales_paym...', Array)
#7 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Resource/Order/Abstract.php(425): Mage_Core_Model_Resource_Db_Abstract->save(Object(Mage_Sales_Model_Order_Payment_Transaction))
#8 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Sales_Model_Resource_Order_Abstract->save(Object(Mage_Sales_Model_Order_Payment_Transaction))
#9 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Order.php(2172): Mage_Core_Model_Abstract->save()
#10 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Sales_Model_Order->_afterSave()
#11 /var/www/vhosts/example.nl/httpdocs/.modman/Icepay_IceAdvanced/app/code/community/Icepay/IceCore/Model/Icepay/Postback.php(88): Mage_Core_Model_Abstract->save()
#12 /var/www/vhosts/example.nl/httpdocs/.modman/Icepay_IceAdvanced/app/code/community/Icepay/IceCore/controllers/ProcessingController.php(24): Icepay_IceCore_Model_Icepay_Postback->handle(Array)
#13 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Icepay_IceCore_ProcessingController->notifyAction()
#14 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('notify')
#15 /var/www/vhosts/example.nl/httpdocs/.modman/Ho_OfflineMaintenance/app/code/local/Ho/OfflineMaintenance/Controller/Router/Standard.php(55): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#18 /var/www/vhosts/example.nl/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /var/www/vhosts/example.nl/httpdocs/index.php(89): Mage::run('nl', 'store')
#20 {main}";s:3:"url";s:36:"/index.php/icepay/processing/notify/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"nl";}
```

**Comment by RicardoJ** [comment]
Thank you for creating a issue. Hopefully we can debug this as fast as possible.

Could you provide the following information?

What | Version
------------ | -------------
Magento version | x.x.x.x
Magento edition | xx
ICEPAY version | x.x.x

The `Exception::getTraceAsString` native method in PHP cuts the backtrace output, and it seems there's no normal way to handle it. With this information we cannot fully debug the issue and provide a patch.

Please backup the files before you going to edit them. Place this function inside this file `app\code\core\Mage\Core\functions.php`:

    function getExceptionTraceAsString($exception)
    {
        $rtn = "";
        $count = 0;
    
        foreach ($exception->getTrace() as $frame){
            $args = "";
    
            if (isset($frame['args'])) {
                $args = array();
                foreach ($frame['args'] as $arg) {
                    if (is_string($arg)) {
                        $args[] = "'" . $arg . "'";
                    } elseif (is_array($arg)) {
                        $args[] = "Array";
                    } elseif (is_null($arg)) {
                        $args[] = 'NULL';
                    } elseif (is_bool($arg)) {
                        $args[] = ($arg) ? "true" : "false";
                    } elseif (is_object($arg)) {
                        $args[] = get_class($arg);
                    } elseif (is_resource($arg)) {
                        $args[] = get_resource_type($arg);
                    } else {
                        $args[] = $arg;
                    }
                }
                $args = join(", ", $args);
            }
    
            $rtn .= sprintf("#%s %s(%s): %s%s(%s)\n",
                $count,
                $frame['file'],
                $frame['line'],
                isset($frame['class']) ? $frame['class'] . '->' : '',
                $frame['function'],
                $args);
    
            $count++;
        }
    
        return $rtn;
    }

Within `app/Mage.php`, look for the `public static function printException` around line 889 and replace the two `$e->getTraceAsString()` you find there with `getExceptionTraceAsString($e)`

Could you also provide a dump of your access and error log files of Apache/Nginx and if there are any, reports from Magento in /var/reports/

**Comment by chrisonderwater** [comment]
Thank you for the fast response,

What | Version
------------ | -------------
Magento version | 1.9.0.1
Magento edition  | Community edition 
ICEPAY version | 1.2.2

I have installed your function, now we will have to wait until a new exception comes up.

Unfortunately I currently have no access to the apache logs since I have no root access. I might be able to obtain them later.

Report folder consists of many files, of which most are: " General error: 2013 Lost connection to MySQL server during query".

Another exception that occured once:

```
a:5:{i:0;s:36:"Niet ondersteund transactie type "".";i:1;s:2450:"#0 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment/Transaction.php(775): Mage::throwException('Niet ondersteun...')
#1 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment/Transaction.php(209): Mage_Sales_Model_Order_Payment_Transaction->_verifyTxnType(false)
#2 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(1231): Mage_Sales_Model_Order_Payment_Transaction->setTxnType(false)
#3 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(1284): Mage_Sales_Model_Order_Payment->_addTransaction(false, NULL, false)
#4 /var/www/vhosts/example.nl/httpdocs/.modman/Icepay_IceAdvanced/app/code/community/Icepay/IceCore/Model/Icepay/Postback.php(191): Mage_Sales_Model_Order_Payment->addTransaction(false, NULL, false)
#5 /var/www/vhosts/example.nl/httpdocs/.modman/Icepay_IceAdvanced/app/code/community/Icepay/IceCore/Model/Icepay/Postback.php(54): Icepay_IceCore_Model_Icepay_Postback->saveTransaction(Array)
#6 /var/www/vhosts/example.nl/httpdocs/.modman/Icepay_IceAdvanced/app/code/community/Icepay/IceCore/controllers/ProcessingController.php(24): Icepay_IceCore_Model_Icepay_Postback->handle(Array)
#7 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Icepay_IceCore_ProcessingController->notifyAction()
#8 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('notify')
#9 /var/www/vhosts/example.nl/httpdocs/.modman/Ho_OfflineMaintenance/app/code/local/Ho/OfflineMaintenance/Controller/Router/Standard.php(55): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/vhosts/example.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/vhosts/example.nl/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/vhosts/example.nl/httpdocs/index.php(89): Mage::run('nl', 'store')
#14 {main}";s:3:"url";s:36:"/index.php/icepay/processing/notify/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"nl";}
```

**Comment by RicardoJ** [comment]
Thank you for your information. As soon as a new exception is generated, please post it in this issue.
